Added cards to the home page.
EotvosCollegium/pluto pull request #5
Opened 2021-09-09 08:31 UTC by viktorcsimma

Tested the Materialize grid and the "card" template.

2021-09-10 13:15 UTC, kdmnk requested changes
Make it more personal! Delete the default texts and create an easter egg, add jokes, something... Play a bit with it.

2021-09-10 16:37 UTC, viktorcsimma commented
I have created a terminal-like box with some interesting content ;) Hope I've added the second commit correctly.

2021-09-10 16:42 UTC, kdmnk commented
Nice. Will merge in class.

2021-09-13 18:11 UTC, kdmnk approved these changes

2021-09-13 18:13 UTC, merged